version: '3.9'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-07T06-41-25Z-cpuv1
    command: minio server /app/data  --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /app/data

  dynamodb:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - 8000:8000
    volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
