#!/usr/bin/env bash

aws dynamodb create-table \
    --table-name Media-Diy \
    --table-class STANDARD_INFREQUENT_ACCESS \
    --attribute-definitions \
        AttributeName=HashKey,AttributeType=S \
        AttributeName=RangeKey,AttributeType=S \
    --key-schema \
        AttributeName=HashKey,KeyType=HASH \
        AttributeName=RangeKey,KeyType=RANGE \
    --billing-mode PAY_PER_REQUEST \
    --endpoint-url http://localhost:8000 \
    --region ap-southeast-2 \
    --deletion-protection
