name: Deploy Staging

on:
  workflow_run:
    workflows: ["Automated Tests"]
    types:
      - completed

jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sleep
        run: sleep 30
      - name: run test
        run: echo true
