name: Automated Tests

on:
  - push

jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: pnpm/action-setup@v4
      - name: pnpm install
        run: pnpm install
      - name: format
        run: pnpm format-check
      - name: lint
        run: pnpm lint
      - name: typecheck
        run: pnpm typecheck
      - name: vitest
        run: pnpm test

  cloud-integration:
    name: cloud-integration
    runs-on: ubuntu-latest
    if: ${{ secrets.CLOUDFLARE_API_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: pnpm/action-setup@v4
      - name: pnpm install
        run: pnpm install
      - name: vitest integration
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: pnpm test:integration

  call-workflow-passing-data:
    if: github.ref == 'refs/heads/main'
    needs:
      - test
    uses: ./.github/workflows/deploy-production.yml
    secrets: inherit
